import { SampleLauncher } from "./sample-launcher.tsx";
import { useRef, useState } from "react";
import { api } from "./api.ts";
const choices = [
  {
    id: "zip",
    label: "Upload source code",
    helper: "Upload a ZIP containing your Node.js or React source files.",
  },
  {
    id: "import",
    label: "Upload scan report",
    helper: "Upload a JSON report generated by the scanner.",
  },
  {
    id: "cli",
    label: "Scan on your computer",
    helper: "Scan a project in your terminal, then upload the results.",
  },
];
export const SCAN_COMMAND =
  "npm run scan -- /path/to/your-project --output /tmp/green-it-report.json";
export function NewAnalysis({
  onDone,
  onStarted,
}: {
  onDone: (id: string) => void;
  onStarted: (id: string) => void;
}) {
  return (
    <>
      <div className="page-heading">
        <div>
          <h1>Analyse application</h1>
          <p>
            Select source, analyse its code and collect supported workload
            evidence.
          </p>
        </div>
      </div>
      <SampleLauncher onStarted={onStarted} />
      <details className="card">
        <summary>Upload source code (ZIP)</summary>
        <SourceTools onDone={onDone} />
      </details>
    </>
  );
}
function SourceTools({ onDone }: { onDone: (id: string) => void }) {
  const [mode, setMode] = useState("zip"),
    [name, setName] = useState(""),
    [file, setFile] = useState<File | null>(null),
    [sample, setSample] = useState(false),
    [busy, setBusy] = useState(false),
    [error, setError] = useState(""),
    [copied, setCopied] = useState(false);
  const formRef = useRef<HTMLFormElement>(null);
  function choose(id: string) {
    setMode(id);
    setFile(null);
    setSample(false);
    setError("");
    setCopied(false);
  }
  const choice = choices.find((c) => c.id === mode)!;
  return (
    <>
      <details className="advanced-source-tools">
        <summary>Advanced options — report import and local scanner</summary>
        <div
          className="analysis-tabs"
          role="tablist"
          aria-label="Analysis method"
        >
          {choices.map((c, i) => (
            <button
              key={c.id}
              id={"tab-" + c.id}
              type="button"
              role="tab"
              aria-selected={mode === c.id}
              aria-controls="analysis-panel"
              tabIndex={mode === c.id ? 0 : -1}
              disabled={busy}
              onClick={() => choose(c.id)}
              onKeyDown={(e) => {
                const next =
                  e.key === "ArrowRight"
                    ? (i + 1) % choices.length
                    : e.key === "ArrowLeft"
                      ? (i + choices.length - 1) % choices.length
                      : e.key === "Home"
                        ? 0
                        : e.key === "End"
                          ? choices.length - 1
                          : null;
                if (next !== null) {
                  e.preventDefault();
                  choose(choices[next].id);
                  document.getElementById("tab-" + choices[next].id)?.focus();
                }
              }}
            >
              {c.label}
            </button>
          ))}
        </div>
      </details>
      <section
        className="card form-card"
        id="analysis-panel"
        role="tabpanel"
        aria-labelledby={"tab-" + mode}
      >
        {mode === "cli" ? (
          <>
            <h2>Scan a project on your computer</h2>
            <p>{choice.helper}</p>
            <p>
              Useful for large projects or when you prefer to keep source files
              on your computer.
            </p>
            <ol className="instruction-list">
              <li>Open a terminal in the Green IT Insights repository.</li>
              <li>
                Run the scanner, replacing the project path with your
                application folder.
                <div className="command-block">
                  <pre>
                    <code>{SCAN_COMMAND}</code>
                  </pre>
                  <button
                    className="secondary"
                    type="button"
                    onClick={async () => {
                      try {
                        await navigator.clipboard.writeText(SCAN_COMMAND);
                        setCopied(true);
                        setError("");
                      } catch {
                        setError(
                          "The command could not be copied. Select the command above and copy it manually.",
                        );
                      }
                    }}
                  >
                    {copied ? "Copied" : "Copy command"}
                  </button>
                </div>
                <span role="status" className="subtle">
                  {copied ? "Command copied to clipboard." : ""}
                </span>
                <p className="subtle">
                  Replace <code>/path/to/your-project</code> with your
                  application folder. The report is written to{" "}
                  <code>/tmp/green-it-report.json</code>, outside that folder.
                  Choose a new output filename if it already exists; the scanner
                  does not overwrite reports.
                </p>
              </li>
              <li>
                Upload the generated JSON file using “Upload scan report.”
              </li>
            </ol>
            <button className="primary" onClick={() => choose("import")}>
              Upload scan report
            </button>
            <p className="subtle trailing-note">
              The scanner does not execute your application.
            </p>
            <details>
              <summary>Advanced options</summary>
              <p>
                For a monorepo, replace the project path with the specific
                package or subdirectory to scan. Add{" "}
                <code>--exclude 'vendor/**'</code> or repeat{" "}
                <code>--exclude</code> for additional patterns. Ignore files
                apply by default.
              </p>
              <p>
                The command runs through this repository’s npm script. No
                globally installed scanner is required. Choose a writable output
                path outside the scanned folder.
              </p>
            </details>
            {error && (
              <p className="error" role="alert">
                {error}
              </p>
            )}
          </>
        ) : (
          <form
            ref={formRef}
            onSubmit={async (e) => {
              e.preventDefault();
              if (!file || busy) return;
              setBusy(true);
              setError("");
              try {
                if (file.size > 10 * 1024 * 1024)
                  throw new Error("Choose a file no larger than 10 MiB.");
                let response;
                if (mode === "zip") {
                  const data = new FormData();
                  data.append("projectName", name);
                  data.append("synthetic", String(sample));
                  data.append("archive", file);
                  response = await api(
                    "/upload",
                    { method: "POST", body: data },
                    "upload source code",
                  );
                } else {
                  let report;
                  try {
                    report = JSON.parse(await file.text());
                  } catch {
                    throw new Error(
                      "This file is not valid JSON. Choose a JSON report generated by the scanner.",
                    );
                  }
                  response = await api(
                    "/import",
                    {
                      method: "POST",
                      headers: { "Content-Type": "application/json" },
                      body: JSON.stringify({ projectName: name, report }),
                    },
                    "upload the scan report",
                  );
                }
                onDone(response.id);
              } catch (e) {
                setError((e as Error).message);
              } finally {
                setBusy(false);
              }
            }}
          >
            <h2>{choice.label}</h2>
            <p>{choice.helper}</p>
            {mode === "import" && (
              <p>
                Run the scanner on your computer to create this file.
                Source-code excerpts are not included in the scanner’s default
                report; file paths and findings are included.
              </p>
            )}
            <label>
              Project name
              <input
                required
                maxLength={100}
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="e.g. Inventory Service"
                disabled={busy}
              />
            </label>
            <p className="subtle">
              Use the same project name for scans you want to compare.
            </p>
            <label key={mode}>
              {mode === "zip" ? "Source code ZIP" : "Scan report (.json)"}
              <input
                type="file"
                required
                accept={mode === "zip" ? ".zip" : ".json"}
                disabled={busy}
                onChange={(e) => {
                  setFile(e.target.files?.[0] ?? null);
                  setError("");
                }}
              />
            </label>
            {mode === "zip" ? (
              <>
                <p className="subtle">
                  Exact bundled Express ZIPs also run the trusted sample
                  workload automatically. Other archives receive static findings
                  only. Maximum ZIP size: 10 MiB. Exclude node_modules and build
                  outputs before uploading.
                </p>
                <details>
                  <summary>Archive requirements</summary>
                  <p>
                    Up to 50 MiB expanded, 3,000 entries and 1 MiB per file.
                    Unsafe paths, symlinks and encrypted entries are rejected.
                    Nested archives are not unpacked. Uploaded source is deleted
                    after analysis.
                  </p>
                </details>
                <details>
                  <summary>Additional options</summary>
                  <label className="check">
                    <input
                      type="checkbox"
                      checked={sample}
                      disabled={busy}
                      onChange={(e) => setSample(e.target.checked)}
                    />
                    This is sample data
                  </label>
                  <p className="subtle">
                    Select this for example projects used in demonstrations.
                  </p>
                </details>
              </>
            ) : (
              <>
                <p className="subtle">Maximum JSON file size: 10 MiB.</p>
                <details>
                  <summary>Report information</summary>
                  <p>
                    Accepts version 1.0 scanner reports. Report structure is
                    validated, but imported findings are not independently
                    verified. Original versions, timestamps, coverage and
                    sample-data labels are preserved.
                  </p>
                </details>
              </>
            )}
            {error && (
              <div className="error" role="alert">
                <span>{error}</span>
                <button
                  type="button"
                  className="secondary"
                  disabled={busy}
                  onClick={() => formRef.current?.requestSubmit()}
                >
                  Retry
                </button>
              </div>
            )}
            <div className="form-actions">
              <button className="primary" disabled={busy || !file}>
                {busy
                  ? "Uploading…"
                  : mode === "zip"
                    ? "Start analysis"
                    : "Upload report"}
              </button>
            </div>
          </form>
        )}
      </section>
    </>
  );
}
